# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clima.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'clima.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lima.proto\"$\n\x12TemperaturaRequest\x12\x0e\n\x06\x63idade\x18\x01 \x01(\t\"*\n\x13TemperaturaResponse\x12\x13\n\x0btemperatura\x18\x01 \x01(\x05\x32S\n\x0c\x43limaService\x12\x43\n\x14MonitorarTemperatura\x12\x13.TemperaturaRequest\x1a\x14.TemperaturaResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clima_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATURAREQUEST']._serialized_start=15
  _globals['_TEMPERATURAREQUEST']._serialized_end=51
  _globals['_TEMPERATURARESPONSE']._serialized_start=53
  _globals['_TEMPERATURARESPONSE']._serialized_end=95
  _globals['_CLIMASERVICE']._serialized_start=97
  _globals['_CLIMASERVICE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
