# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuario.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'usuario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\x12\x05unary\"\x1c\n\x0eUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x0fUsuarioResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05idade\x18\x02 \x01(\x05\x32P\n\x0eUsuarioService\x12>\n\rBuscarUsuario\x12\x15.unary.UsuarioRequest\x1a\x16.unary.UsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIOREQUEST']._serialized_start=24
  _globals['_USUARIOREQUEST']._serialized_end=52
  _globals['_USUARIORESPONSE']._serialized_start=54
  _globals['_USUARIORESPONSE']._serialized_end=100
  _globals['_USUARIOSERVICE']._serialized_start=102
  _globals['_USUARIOSERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
